name: Web CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'web/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'web/**'

jobs:
  build-and-test:
    runs-on:  ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    defaults:
      run:
        working-directory: ./web
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pnpm 
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

    - name: Install dependencies
      run: pnpm install

    - name: Run Vitest
      run: pnpm exec vitest --run